# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hl8kY7rs_cIzQvqbUz9NaDLxrAzQLNtD
"""

rows = 5
for i in range(1, rows + 1):
    print("* " * i)

rows = 5
for i in range(rows, 0, -1):
    print("* " * i)

rows = 5
for i in range(1, rows + 1):
    spaces = ' ' * (rows - i)
    stars = '* ' * i
    print(spaces + stars)

